# Copyright (c) 2016, Daniele Venzano
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Exceptions used by the API component."""


class ZoeException(Exception):
    """
    A generic exception.
    """
    def __init__(self, message='Something happened'):
        super().__init__()
        self.message = message

    def __str__(self):
        return self.message


class ZoeAuthException(ZoeException):
    """An authentication error."""
    pass


class ZoeNotFoundException(ZoeException):
    """Th euser is looking for an object that does not exist."""
    pass


class ZoeRestAPIException(ZoeException):
    """
    An exception generated by the REST API.
    """
    def __init__(self, message, status_code=400, headers=None):
        super().__init__(message)
        self.status_code = status_code
        self.headers = headers

    def __str__(self):
        return '[{}] {}'.format(self.status_code, self.message)
