class ZoeException(Exception):
    """
    A generic exception.
    """
    def __init__(self, value='Something happened'):
        self.value = value

    def __str__(self):
        return self.value


class ZoeAPIException(Exception):
    """
    An exception generated by the API.
    """
    def __init__(self, message):
        self.message = message

    def __str__(self):
        return repr(self.message)


class InvalidApplicationDescription(ZoeAPIException):
    """
    An exception thrown while parsing an application description.
    """
    def __init__(self, msg):
        self.message = "Error: " + msg


class ZoeRestAPIException(ZoeException):
    """
    An exception generated by the REST API.

    TODO: should be merged with ZoeAPIException.
    """
    def __init__(self, message, status_code=400, headers=None):
        super().__init__(value=message)
        self.status_code = status_code
        self.headers = headers
